name: eiu-pchem-env
channels:
  - conda-forge
  - veloxchem
dependencies:
  - python>=3.12
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - dftd3-python
  - dftd4-python
  - veloxchem
  - rdkit
  - plotly
  - py3Dmol
  - ase
  - jupyterlab
  - ipywidgets
  - nodejs